import {
  QUOTATION_DOCUMENT_SCHEMA_VERSION,
  type QuotationDocumentDataV1,
} from "@/lib/quotation-documents/types"

const itinerary = [
  ["Llegada a San Pedro de Atacama", "Recepción en el aeropuerto de Calama y traslado hacia San Pedro de Atacama. Tiempo libre para aclimatarse a la altura, recorrer el centro y preparar el equipaje para las excursiones."],
  ["Valle de la Luna", "Salida por la tarde hacia la Cordillera de la Sal. Visita a formaciones naturales, miradores y senderos del Valle de la Luna. Regreso luego de la puesta del sol."],
  ["Lagunas Altiplánicas", "Excursión de día completo por el altiplano. Recorrido por lagunas, salares y pueblos tradicionales, con desayuno y almuerzo incluidos durante la jornada."],
  ["Géiseres del Tatio", "Salida de madrugada hacia el campo geotérmico. Desayuno al amanecer, observación de fumarolas y regreso con paradas panorámicas y avistaje de fauna."],
  ["San Pedro a Uyuni", "Inicio de la travesía internacional en vehículo 4x4. Cruce fronterizo, lagunas de colores, desierto de Dalí y aguas termales. Noche en alojamiento de montaña."],
  ["Desierto de Siloli", "Recorrido por formaciones de roca, volcanes y lagunas habitadas por flamencos. Continuación hacia un alojamiento de sal, con pensión completa."],
  ["Salar de Uyuni", "Ingreso al salar, visita a la Isla Incahuasi cuando las condiciones lo permiten y sesión fotográfica de perspectiva. Almuerzo y llegada a la ciudad de Uyuni."],
  ["Uyuni", "Día disponible para recorrer la ciudad, el mercado local y el cementerio de trenes. Coordinación de actividades opcionales con el guía."],
  ["Regreso a San Pedro", "Inicio del regreso por el altiplano, con paradas técnicas y paisajísticas. Noche en ruta y asistencia permanente del equipo local."],
  ["Fin del programa", "Cruce de frontera y traslado final a San Pedro de Atacama o al aeropuerto, según el horario del vuelo contratado."],
] as const

export const KYO_FULL_ITINERARY_FIXTURE: QuotationDocumentDataV1 = {
  schemaVersion: QUOTATION_DOCUMENT_SCHEMA_VERSION,
  identity: {
    quotationId: "fixture-kyo-2026",
    quotationNumber: "KYO-2026-001",
    title: "San Pedro de Atacama + Salar de Uyuni",
    createdAt: "2026-08-24T12:00:00.000Z",
    validUntil: "2026-08-31",
    status: "DRAFT",
  },
  agency: {
    id: "fixture-agency-kyo",
    name: "KYO Viajes y Turismo",
    email: "ventas@kyo.tur.ar",
    phone: "+54 9 11 0000 0000",
    travelLicense: "Leg. 13123",
  },
  customer: {
    displayName: "Cliente de ejemplo",
    email: "cliente@ejemplo.com",
  },
  advisor: {
    displayName: "Asesora KYO",
    email: "asesora@kyo.tur.ar",
  },
  trip: {
    destination: "San Pedro de Atacama y Uyuni",
    origin: "Buenos Aires",
    region: "SUDAMÉRICA",
    departureDate: "2026-10-03",
    returnDate: "2026-10-14",
    adults: 2,
    children: 0,
    infants: 0,
  },
  options: [1, 2, 3, 4].map(index => ({
    id: `fixture-option-${index}`,
    number: index,
    title: index === 1 ? "Programa recomendado" : `Alternativa ${index}`,
    totalAmount: 4_800 + index * 250,
    selected: index === 1,
    items: [
      {
        id: `flight-${index}`,
        type: "FLIGHT",
        description: "Vuelos internacionales y regionales",
        provider: "LATAM Airlines",
        quantity: 1,
        flight: {
          airline: "LATAM Airlines",
          cabin: "Economy",
          route: "Buenos Aires - Santiago - Calama",
          departureDate: "2026-10-03",
          returnDate: "2026-10-14",
          legs: [
            {
              departureCode: "EZE",
              departureCity: "Buenos Aires",
              departureTime: "07:40",
              arrivalCode: "SCL",
              arrivalCity: "Santiago",
              arrivalTime: "10:05",
              duration: "2 h 25 min",
              baggage: "Carry on y equipaje despachado",
              layovers: [],
            },
            {
              departureCode: "SCL",
              departureCity: "Santiago",
              departureTime: "12:15",
              arrivalCode: "CJC",
              arrivalCity: "Calama",
              arrivalTime: "14:25",
              duration: "2 h 10 min",
              baggage: "Carry on y equipaje despachado",
              layovers: [],
            },
          ],
        },
      },
      {
        id: `hotel-${index}`,
        type: "HOTEL",
        description: "Alojamiento seleccionado",
        quantity: 1,
        hotel: {
          name: index === 1 ? "Hotel Altiplánico" : `Hotel alternativa ${index}`,
          stars: 4,
          roomType: "Habitación doble",
          mealPlan: "Desayuno",
          checkinDate: "2026-10-03",
          checkoutDate: "2026-10-14",
          nights: 11,
          rooms: 1,
          destination: "San Pedro de Atacama / Uyuni",
        },
      },
      {
        id: `transfer-${index}`,
        type: "TRANSFER",
        description: "Traslados privados y vehículo 4x4 durante la travesía",
        quantity: 1,
        transfer: { description: "Aeropuerto, hoteles y frontera" },
      },
    ],
  })),
  narrative: {
    overview: "Una travesía por paisajes andinos que combina el desierto de Atacama con el Salar de Uyuni, acompañamiento local y servicios seleccionados.",
    inclusions: [
      "Vuelos detallados en la propuesta",
      "Traslados de llegada y salida",
      "Alojamiento con desayuno",
      "Travesía en vehículo 4x4",
      "Guía local y comidas indicadas",
      "Asistencia al viajero",
    ],
    exclusions: [
      "Gastos personales y propinas",
      "Comidas no mencionadas",
      "Tasas migratorias o entradas no indicadas",
    ],
    itinerary: itinerary.map(([title, description], index) => ({
      day: index + 1,
      title,
      description,
    })),
    recommendations: [
      "Llevar abrigo por capas, protector solar y calzado cómodo.",
      "Consultar al médico antes del viaje por la permanencia en altura.",
      "Mantener hidratación constante y respetar los tiempos de aclimatación.",
    ],
    restrictions: [
      "El orden de las excursiones puede modificarse por clima, caminos o disposiciones fronterizas.",
      "Los pasajeros deben contar con documentación migratoria vigente.",
    ],
  },
  commercial: {
    currency: "USD",
    pricingMode: "GROUP_TOTAL",
    insuranceAmount: 180,
    transferAmount: 220,
    depositAmount: 500,
    balanceDueDate: "2026-09-05",
    paymentMethods: ["Transferencia bancaria", "Efectivo", "Tarjeta según condiciones"],
    paymentSchedule: [
      { label: "Reserva", amount: 500, dueDate: "2026-08-31" },
      { label: "Saldo", dueDate: "2026-09-05", notes: "Sujeto a la cotización del día de pago." },
    ],
    terms: [
      "Todos los servicios están sujetos a disponibilidad hasta su confirmación.",
      "Las tarifas pueden variar por cambios de disponibilidad, impuestos o tipo de cambio.",
      "Las condiciones de cancelación se informan al confirmar cada servicio.",
      "La documentación y requisitos migratorios son responsabilidad del pasajero.",
    ],
  },
}

